name: FHiddenMine
main: moe.berd.nukkit.FHiddenMine.Main
version: 1.0.4
load: POSTWORLD
author: FENGberd

api: ["1.0.0"]

permissions:
 FHiddenMine.show:
  description: "Don't hide mine for this player."
  default: op
